 - name: Install and configure cockpit
   hosts: webservers
   gather_facts: false
   become: yes
   tasks:
     - name: EL Family | Adding repository {{ googlechrome_repo_el }}
       yum_repository:
         name: "{{ googlechrome_repo_el_name }}"
         description: "{{ googlechrome_repo_el_description }}"
         baseurl: "{{ googlechrome_repo_el }}"
         gpgcheck: "{{ googlechrome_repo_el_gpgcheck }}"
         gpgkey: "{{ googlechrome_gpg_key }}"
         file: "{{ googlechrome_repo_el_filename }}"
         state: "{{ googlechrome_repo_desired_state }}"
         enabled: "{{ googlechrome_repo_el_enabled }}"
    - name: EL Family | Installing {{ googlechrome_app_name }}
      yum:
         name: "{{ googlechrome_app_name }}"
         state: "{{ googlechrome_desired_state }}"
         update_cache: yes
