 - name: ZOOM Testing
   hosts: win
   gather_facts: false
   become: false
   tasks:
   
   - name: Install chocolatey
     win_chocolatey:
      name:
          - chocolatey
          - chocolatey-core.extension
      state: present

   - name: Install multiple packages
     win_chocolatey:
      name:
       - procexp
       - putty
       - windirstat
      state: present
 