 - name: ZOOM Testing
   hosts: win
   gather_facts: false
   become: false
   tasks:
   
   - name: Install chocolatey
     win_chocolatey:
      name:
          - chocolatey
          - chocolatey-core.extension
      state: present

   - name: Install Google Chrome
     win_chocolatey:
       name: googlechrome
       state: present
 