 - name: ZOOM Testing
   hosts: win
   gather_facts: false
   become: false
   tasks:
   - name: Copy Installer to WIN
     win_copy:
      src: ChromeSetup.exe
      dest: C:\

   - name: "Chocolatey"
     hosts: windows
     tasks:
   - name: Install chocolatey
     win_chocolatey:
       name:
          - chocolatey
          - chocolatey-core.extension
       state: present

   - name: Install Google Chrome
     win_chocolatey:
        name: googlechrome
        state: present
        ignore_checksums: yes
    #- name: Install Chrome locally omitting the product_id
     #win_package:
      # path: C:\ChromeSetup.exe
       #productid: auto
       #state: present
 