 - name: ZOOM Testing
   hosts: win
   gather_facts: false
   become: false
   tasks:
   - name: Download Zoom
     win_get_url:
       url: https://https://zoom.us/client/5.9.3.3169/ZoomInstaller.exe?archType=x64
       dest: C:\Zoominstaller.exe
       productid: auto
       state: present

   - name: Install Remote Desktop Connection Manager locally omitting the product_id
     win_package:
       path: C:\Zoominstaller.exe
       productid: auto
       state: present

  


   # name: Downloading ZOOM
    # win_command: C:\Zoominstaller.exe /i C:\temp\7z.msi /qn /norestart
     # state: present
    